void *throttler(void *args);
int irc_send_raw_throttled(struct irc_session *session, const char *format, ...) __attribute((__format__(printf, 2, 3))) __attribute__((__nonnull__(1, 2)));
int irc_cmd_channel_mode_throttled(struct irc_session *session, const char *channel, const char *mode) __attribute__((__nonnull__(1, 2)));
int irc_cmd_ctcp_reply_throttled(struct irc_session *session, const char *nick, const char *reply) __attribute__((__nonnull__));
int irc_cmd_ctcp_request_throttled(struct irc_session *session, const char *nch, const char *request) __attribute__((__nonnull__));
int irc_cmd_invite_throttled(struct irc_session *session, const char *nick, const char *channel) __attribute__((__nonnull__));
int irc_cmd_join_throttled(struct irc_session *session, const char *channel, const char *key) __attribute__((__nonnull__(1, 2)));
int irc_cmd_kick_throttled(struct irc_session *session, const char *nick, const char *channel, const char *reason) __attribute__((__nonnull__(1, 2)));
int irc_cmd_list_throttled(struct irc_session *session, const char *channel) __attribute__((__nonnull__(1)));
int irc_cmd_me_throttled(struct irc_session *session, const char *nch, const char *text) __attribute__((__nonnull__));
int irc_cmd_msg_throttled(struct irc_session *session, const char *nch, const char *text) __attribute__((__nonnull__));
int irc_cmd_msg_to_throttled(struct irc_session *session, const char *channel, const char *to, const char *text) __attribute__((__nonnull__));
int irc_cmd_names_throttled(struct irc_session *session, const char *channel) __attribute__((__nonnull__));
int irc_cmd_nick_throttled(struct irc_session *session, const char *newnick) __attribute__((__nonnull__));
int irc_cmd_notice_throttled(struct irc_session *session, const char *nch, const char *text) __attribute__((__nonnull__));
int irc_cmd_part_throttled(struct irc_session *session, const char *channel, const char *reason) __attribute__((__nonnull__(1, 2)));
int irc_cmd_quit_throttled(struct irc_session *session, const char *reason) __attribute__((__nonnull__(1)));
int irc_cmd_topic_throttled(struct irc_session *session, const char *channel, const char *topic) __attribute__((__nonnull__(1, 2)));
int irc_cmd_user_mode_throttled(struct irc_session *session, const char *mode) __attribute__((__nonnull__(1)));
int irc_cmd_whois_throttled(struct irc_session *session, const char *nick) __attribute__((__nonnull__));
